### ISSUE TITLE
Why don't share the code

### ISSUE THREAD

**Issue by theotheo** [mdh266/AirflowBlogPost#1]
At first, thank you for the pretty nice tutorial!  

But why images? Why don't share the code? Just out of curiosity.

**Comment by mdh266** [comment]
Thanks!  I didn't know how to add the code with the highlighting I wanted so I just added it as an image.  If you like, you can find the source code for that here: https://github.com/mdh266/AirflowDataPipeline

**Comment by theotheo** [comment]
Gotcha! Thanks again!
